# Generated by Django 4.2.6 on 2023-10-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='mehsulin adi')),
                ('herz', models.CharField(max_length=255, verbose_name='herz')),
                ('color', models.CharField(max_length=255, verbose_name='mehsulun rengi')),
                ('price', models.CharField(max_length=255, verbose_name='pehsulun qiymeti')),
                ('marka', models.CharField(max_length=255, verbose_name='mehsulun markasi')),
            ],
            options={
                'verbose_name': 'mehsulin adi',
                'verbose_name_plural': 'mehsulin adlari',
                'ordering': ('marka',),
            },
        ),
    ]
